#开发环境
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/train?characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: 2001zhaohu0629.
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid的其他属性配置
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 连接池的最小空闲数量
      min-idle: 5
      # 连接池最大连接数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000

      # 主要配置以上几个即可
      timeBetweenEvictionRunsMillis: 600000
      #配置一个连接在池中最大空间时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      #设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
      testOnBorrow: true
      #设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
      testOnReturn: true
      #可以支持PSCache（提升写入、查询效率）
      poolPreparedStatements: true


      #配置监控统计拦截的filters
      filter:
        #self4j(使用log4j的记得导入log4j的依赖）：日志记录
        slf4j:
          enabled: true
        #stat:监控统计
        stat:
          enabled: true
        #wall：防御sql注入 此处配置不能遗漏服务sql监控台不能监控sql
        wall:
          enabled: true
      #配置stat-view-servlet
      stat-view-servlet:
        # 是否启用StatViewServlet默认值false
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台，默认为root
        login-username: druid
        login-password: druid
        # IP白名单
        allow: 127.0.0.1
        # IP黑名单（共同存在时，deny优先于allow）
        deny:
      #配置web-stat-filter
      web-stat-filter:
        # 是否启用StatFilter默认值false
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
server:
  port: 8888
#mybatis整合
mybatis:
  configuration:
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名法自动映射
    map-underscore-to-camel-case: true
    #查询语句中某些字段值是null的,是否返回
    return-instance-for-empty-row: true
  #指定映射文件的位置
  mapper-locations: classpath*:dao/*.xml
  #指定别名
  type-aliases-package: com.study.springboot.domain
#mybatis-plus整合
mybatis-plus:
  configuration:
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
